/**
 * The content layer.
 *
 *   profile.ts      who I am: name, links, languages, education
 *   site.ts         what the document needs: canonical url, search snippet
 *   areas.ts        the kinds of work, which are also the routes
 *   roles.ts        the jobs
 *   work.ts         everything I have done, as one flat list
 *   stack.ts        the technologies
 *   brand-icons.ts  GENERATED by `yarn icons:sync`, never hand-edited
 *
 * This file is the only entry point. Everything imports from "@/content", so
 * moving a file inside here never touches a component.
 */
import { work, type WorkItem } from "./work";
import { AREAS, type Area } from "./areas";
import { roles, type Role, type RoleId } from "./roles";
import { brandIcons, type BrandIcon } from "./brand-icons";
import {
  STACK_GROUPS,
  stack,
  type StackGroup,
  type StackId,
  type StackItem,
} from "./stack";

export * from "./profile";
export * from "./site";
export * from "./areas";
export * from "./roles";
export * from "./work";
export * from "./stack";
export * from "./brand-icons";

const stackById = new Map<string, StackItem>(stack.map((s) => [s.id, s]));
const roleById = new Map<string, Role>(roles.map((r) => [r.id, r]));

/**
 * Both indexes are derived from the single `work` list, so the Stack view and
 * the Work view stay in step by construction. Adding one item populates
 * everything it links to, and there is no second list to update.
 */
const byStack = new Map<string, WorkItem[]>();
const byRole = new Map<string, WorkItem[]>();
const byArea = new Map<Area, WorkItem[]>(AREAS.map((a) => [a, []]));

for (const item of work) {
  byArea.get(item.area)?.push(item);
  for (const id of item.meta?.stack ?? []) {
    const bucket = byStack.get(id);
    if (bucket) bucket.push(item);
    else byStack.set(id, [item]);
  }
  if (item.meta?.role) {
    const bucket = byRole.get(item.meta.role);
    if (bucket) bucket.push(item);
    else byRole.set(item.meta.role, [item]);
  }
}

export function stackItem(id: StackId): StackItem {
  const found = stackById.get(id);
  if (!found) throw new Error(`Unknown stack item: ${id}`);
  return found;
}

/**
 * Where a technology was actually used. Empty means it is an unproven claim.
 *
 * Takes a plain string, unlike `stackItem`: that one asserts and throws, so it
 * stays strict, while this models a miss in its return type.
 */
export function workUsing(id: string): readonly WorkItem[] {
  return byStack.get(id) ?? [];
}

/** What happened inside a role, optionally narrowed to one kind of work. */
export function workAt(id: RoleId, area?: Area): readonly WorkItem[] {
  const items = byRole.get(id) ?? [];
  return area ? items.filter((i) => i.area === area) : items;
}

/**
 * Every piece of work of one kind, whichever role it happened in. This is the
 * index that grows in place: a second role adds items here rather than a page.
 */
export function workIn(area: Area): readonly WorkItem[] {
  return byArea.get(area) ?? [];
}

/** The technologies one item used, resolved to objects for rendering. */
export function stackOf(item: WorkItem): readonly StackItem[] {
  return (item.meta?.stack ?? []).map(stackItem);
}

/**
 * The work the landing shows first, under Highlights: the first six items of
 * `work`, whose order is the site's one ranking.
 */
export const highlights: readonly WorkItem[] = work.slice(0, 6);

export function roleOf(item: WorkItem): Role | undefined {
  return item.meta?.role ? roleById.get(item.meta.role) : undefined;
}

/**
 * The mark for a sprite id, or undefined when there is no licensed one to use.
 * A miss renders a monogram rather than a wrong logo; today that is Kysely.
 */
export function iconFor(id: string): BrandIcon | undefined {
  return brandIcons[id];
}

/**
 * First letters, for anything without a mark: a technology, a company. Keeps
 * every set of marks one system. `short` wins where initials read badly.
 */
export function monogramFor(label: string, short?: string): string {
  if (short) return short;
  return label
    .split(/[\s-]+/)
    .filter((w) => !/^(and|the|of)$/i.test(w))
    .slice(0, 2)
    .map((w) => w[0])
    .join("")
    .toUpperCase();
}

export function stackByGroup(): readonly {
  group: StackGroup;
  items: readonly StackItem[];
}[] {
  return STACK_GROUPS.map((group) => ({
    group,
    items: stack.filter((s) => s.group === group),
  })).filter((g) => g.items.length > 0);
}

/**
 * Health of the graph. Listing a technology nothing demonstrates is exactly the
 * padded-CV problem this model exists to prevent, so `yarn content:check` fails
 * on it rather than shipping a dead entry.
 */
export const unusedStack: readonly StackItem[] = stack.filter(
  (s) => workUsing(s.id).length === 0,
);

/** Items attached to nothing at all. Legal, but usually an oversight. */
export const unlinkedWork: readonly WorkItem[] = work.filter(
  (i) => !i.meta?.role && (i.meta?.stack ?? []).length === 0,
);
